export const SITE = {
  url:           'https://portfolio.pavas.io',
  name:          'Juan Fernando Pavas Garzón',
  jobTitle:      'Full-Stack Developer',
  email:         'garzonp2001@gmail.com',
  github:        'https://github.com/juanpavasgarzon',
  githubHandle:  'juanpavasgarzon',
  linkedin:      'https://www.linkedin.com/in/juanpavasgarzon/',
  twitterHandle: '@juanpavasgarzon',
  avatarUrl:     'https://avatars.githubusercontent.com/u/87050643?v=4',
  ogImageUrl:    'https://portfolio.pavas.io/og-image.svg',
  location:      'Medellín · Rionegro, CO',
  timezone:      'GMT−5',
  techStack:     ['React', 'TypeScript', 'Node.js', 'NestJS', 'Laravel', 'PHP', '.NET', 'Docker', 'MySQL', 'PostgreSQL', 'MongoDB'],
} as const;
